name: React Continuous Integration

on:
  pull_request:
    branches: [master]

jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - cmd: install
      - cmd: build
      - cmd: test
